In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score    
from sklearn.metrics import  precision_score
from sklearn.metrics import   recall_score
from sklearn.metrics import   f1_score
from sklearn.metrics import    confusion_matrix
from sklearn.metrics import  classification_report

In [2]:
dataSet = pd.read_csv('../data/processed/cleaned_reviews.csv')

dataSet.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Review Length,Sentiment
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,53,Positive
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,303,Positive
2,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,124,Positive
3,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,192,Positive
4,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses,488,Negative

In [3]:
dataSet.shape

(19817, 12)

In [4]:
dataSet.info()

<class 'pandas.DataFrame'>
RangeIndex: 19817 entries, 0 to 19816
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              19817 non-null  int64
 1   Age                      19817 non-null  int64
 2   Title                    17211 non-null  str
 3   Review Text              19817 non-null  str
 4   Rating                   19817 non-null  int64
 5   Recommended IND          19817 non-null  int64
 6   Positive Feedback Count  19817 non-null  int64
 7   Division Name            19817 non-null  str
 8   Department Name          19817 non-null  str
 9   Class Name               19817 non-null  str
 10  Review Length            19817 non-null  int64
 11  Sentiment                19817 non-null  str
dtypes: int64(6), str(6)
memory usage: 8.5 MB

In [5]:
dataSet.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name', 'Review Length', 'Sentiment'],
      dtype='str')

In [6]:
dataSet.isnull().sum()

Clothing ID                   0
Age                           0
Title                      2606
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                 0
Department Name               0
Class Name                    0
Review Length                 0
Sentiment                     0
dtype: int64

In [7]:
copyDataSet=dataSet[['Review Text','Recommended IND']].copy()
copyDataSet.head()

                                         Review Text  Recommended IND
0  Absolutely wonderful - silky and sexy and comf...                1
1  Love this dress!  it's sooo pretty.  i happene...                1
2  I love, love, love this jumpsuit. it's fun, fl...                1
3  This shirt is very flattering to all due to th...                1
4  I love tracy reese dresses, but this one is no...                0

In [8]:
copyDataSet.isnull().sum()

Review Text        0
Recommended IND    0
dtype: int64

In [9]:
copyDataSet = copyDataSet.dropna(subset=['Review Text'])
copyDataSet.isnull().sum()

Review Text        0
Recommended IND    0
dtype: int64

In [10]:
copyDataSet.shape

(19817, 2)

In [11]:
x=copyDataSet['Review Text']
y=copyDataSet['Recommended IND']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42, stratify=y)
print("Training:", x_train.shape)
print("Testing:", x_test.shape)

Training: (15853,)
Testing: (3964,)

In [13]:
TF_IDF=TfidfVectorizer(
    stop_words='english',
    max_features=5000,
)
xTrainTdIdf=TF_IDF.fit_transform(x_train)
xTestTdIdf=TF_IDF.transform(x_test)
print(xTrainTdIdf.shape)
print(xTestTdIdf)

(15853, 5000)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 90437 stored elements and shape (3964, 5000)>
  Coords	Values
  (0, 739)	0.5245086377665242
  (0, 1531)	0.3751613674005984
  (0, 2050)	0.14004547461494143
  (0, 2489)	0.32005750319210424
  (0, 2552)	0.13945966831690562
  (0, 3463)	0.2586524578025177
  (0, 3507)	0.3935940025709969
  (0, 3884)	0.27058091171050946
  (0, 4013)	0.2513940225254607
  (0, 4636)	0.2559065670831447
  (0, 4819)	0.1375776497641439
  (1, 32)	0.24169961178648636
  (1, 455)	0.3703004863279389
  (1, 507)	0.19166055126322845
  (1, 558)	0.13839558949786107
  (1, 565)	0.12576956387500562
  (1, 583)	0.2512916847102503
  (1, 1226)	0.12500351309226965
  (1, 1766)	0.07899433964197751
  (1, 1767)	0.10557453228004537
  (1, 2021)	0.12215519346024882
  (1, 2026)	0.11325977192719391
  (1, 2523)	0.11037037205713475
  (1, 2756)	0.19062229660703967
  (1, 2924)	0.2161470148117747
  :	:
  (3963, 462)	0.18981261548731768
  (3963, 933)	0.21723727131270193
  (3963, 1046)	0.16142513446124093
  (3963, 1227)	0.08891459389873392
  (3963, 1389)	0.13767566639101625
  (3963, 1465)	0.20351261801943282
  (3963, 1471)	0.06583609170378799
  (3963, 1481)	0.20188452046117333
  (3963, 1496)	0.15450131885729465
  (3963, 1655)	0.12840173695851445
  (3963, 1960)	0.20804340926316894
  (3963, 1968)	0.1606705485389593
  (3963, 2082)	0.3319514170363653
  (3963, 2319)	0.20614377530407596
  (3963, 2434)	0.42454199534795345
  (3963, 2552)	0.06862902020823924
  (3963, 2565)	0.13590490716692813
  (3963, 2608)	0.08987507506196893
  (3963, 3450)	0.09564788068034387
  (3963, 3726)	0.17059169995599147
  (3963, 3803)	0.17194190308822685
  (3963, 3807)	0.1725004298604709
  (3963, 3939)	0.18781292070143038
  (3963, 4149)	0.18549587535197606
  (3963, 4798)	0.29157413234332435

In [14]:
decTree=DecisionTreeClassifier(
    random_state=42
)
decTree.fit(xTrainTdIdf,y_train)
yPredict=decTree.predict(xTestTdIdf)

In [15]:
accuracy = accuracy_score(y_test, yPredict)
precision = precision_score(y_test, yPredict)
recall = recall_score(y_test, yPredict)
f1 = f1_score(y_test, yPredict)

print("Accuracy:", accuracy*100)
print("Precision:", precision*100)
print("Recall:", recall*100)
print("F1 Score:", f1*100)

Accuracy: 87.00807265388497
Precision: 92.57553956834532
Recall: 92.60218767990789
F1 Score: 92.5888617067204

In [16]:
print(classification_report(y_test, yPredict))

              precision    recall  f1-score   support

           0       0.47      0.47      0.47       490
           1       0.93      0.93      0.93      3474

    accuracy                           0.87      3964
   macro avg       0.70      0.70      0.70      3964
weighted avg       0.87      0.87      0.87      3964

In [17]:
confusionMatrix = confusion_matrix(y_test, yPredict)

print(confusionMatrix)

[[ 232  258]
 [ 257 3217]]