In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score    
from sklearn.metrics import  precision_score
from sklearn.metrics import   recall_score
from sklearn.metrics import   f1_score
from sklearn.metrics import    confusion_matrix
from sklearn.metrics import  classification_report

In [3]:
dataSet = pd.read_csv('../data/raw/Womens Clothing E-Commerce Reviews.csv')

dataSet.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [4]:
dataSet.shape

(23486, 11)

In [5]:
dataSet.info()

<class 'pandas.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  str
 4   Review Text              22641 non-null  str
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  str
 9   Department Name          23472 non-null  str
 10  Class Name               23472 non-null  str
dtypes: int64(6), str(5)
memory usage: 9.5 MB

In [6]:
dataSet.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='str')

In [7]:
dataSet.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
copyDataSet=dataSet[['Review Text','Recommended IND']].copy()
copyDataSet.head()

                                         Review Text  Recommended IND
0  Absolutely wonderful - silky and sexy and comf...                1
1  Love this dress!  it's sooo pretty.  i happene...                1
2  I had such high hopes for this dress and reall...                0
3  I love, love, love this jumpsuit. it's fun, fl...                1
4  This shirt is very flattering to all due to th...                1

In [10]:
copyDataSet.isnull().sum()

Review Text        845
Recommended IND      0
dtype: int64

In [13]:
copyDataSet = copyDataSet.dropna(subset=['Review Text'])
copyDataSet.isnull().sum()

Review Text        0
Recommended IND    0
dtype: int64

In [15]:
copyDataSet.shape

(22641, 2)

In [16]:
x=copyDataSet['Review Text']
y=copyDataSet['Recommended IND']

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42, stratify=y)
print("Training:", x_train.shape)
print("Testing:", x_test.shape)

Training: (18112,)
Testing: (4529,)

In [18]:
TF_IDF=TfidfVectorizer(
    stop_words='english',
    max_features=5000,
)
xTrainTdIdf=TF_IDF.fit_transform(x_train)
xTestTdIdf=TF_IDF.transform(x_test)
print(xTrainTdIdf.shape)
print(xTestTdIdf)

(18112, 5000)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 104014 stored elements and shape (4529, 5000)>
  Coords	Values
  (0, 325)	0.6703455427646745
  (0, 1996)	0.27567921070795887
  (0, 2073)	0.4890393469460855
  (0, 2509)	0.19589729742782858
  (0, 4538)	0.2888345849784731
  (0, 4928)	0.3371604582365839
  (1, 1510)	0.28290822377255764
  (1, 1613)	0.13842909975433568
  (1, 2014)	0.12705899588702588
  (1, 2255)	0.4031174382158783
  (1, 2454)	0.3293870796047602
  (1, 2561)	0.14695046052568025
  (1, 2590)	0.10855553514576496
  (1, 2914)	0.31919483319073294
  (1, 3244)	0.3377222784408523
  (1, 3300)	0.3662353935506677
  (1, 3454)	0.2980425411279891
  (1, 3706)	0.3244988533395016
  (1, 4208)	0.1899451737808316
  (2, 837)	0.1535300644278369
  (2, 993)	0.10148122485353178
  (2, 1201)	0.13422589295221085
  (2, 1223)	0.18675723933544447
  (2, 1280)	0.18245921941251012
  (2, 1424)	0.08628022264346907
  :	:
  (4528, 1308)	0.16868424979403587
  (4528, 1377)	0.12228804341635553
  (4528, 1597)	0.26448349744252914
  (4528, 1753)	0.17103821753191295
  (4528, 1996)	0.09771044764458507
  (4528, 2127)	0.18192146401948855
  (4528, 2159)	0.23065709461458253
  (4528, 2359)	0.07560895500068526
  (4528, 2487)	0.17993596095611578
  (4528, 2509)	0.13886584029954166
  (4528, 2561)	0.08408260983980727
  (4528, 2820)	0.20111151634160912
  (4528, 2911)	0.14968171176588396
  (4528, 3454)	0.08526749290775458
  (4528, 3560)	0.10042928001773148
  (4528, 3870)	0.15479826659064305
  (4528, 3911)	0.15456628208486387
  (4528, 3944)	0.16533182877026786
  (4528, 4055)	0.21535917391784748
  (4528, 4232)	0.1627784027196713
  (4528, 4285)	0.25604121180699063
  (4528, 4396)	0.25604121180699063
  (4528, 4454)	0.1601486544227824
  (4528, 4478)	0.19197214597853612
  (4528, 4822)	0.10479210216369277

In [20]:
decTree=DecisionTreeClassifier(
    random_state=42
)
decTree.fit(xTrainTdIdf,y_train)
yPredict=decTree.predict(xTestTdIdf)

In [22]:
accuracy = accuracy_score(y_test, yPredict)
precision = precision_score(y_test, yPredict)
recall = recall_score(y_test, yPredict)
f1 = f1_score(y_test, yPredict)

print("Accuracy:", accuracy*100)
print("Precision:", precision*100)
print("Recall:", recall*100)
print("F1 Score:", f1*100)

Accuracy: 80.72422168249062
Precision: 88.30361966504591
Recall: 88.13696414127797
F1 Score: 88.22021319659964

In [23]:
print(classification_report(y_test, yPredict))

              precision    recall  f1-score   support

           0       0.47      0.47      0.47       820
           1       0.88      0.88      0.88      3709

    accuracy                           0.81      4529
   macro avg       0.68      0.68      0.68      4529
weighted avg       0.81      0.81      0.81      4529

In [24]:
confusionMatrix = confusion_matrix(y_test, yPredict)

print(confusionMatrix)

[[ 387  433]
 [ 440 3269]]