Linear SVC Model

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import  precision_score
from sklearn.metrics import   recall_score
from sklearn.metrics import   f1_score

In [2]:
df = pd.read_csv('../data/processed/cleaned_reviews.csv')

In [3]:
df.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Review Length,Sentiment
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,53,Positive
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,303,Positive
2,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,124,Positive
3,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,192,Positive
4,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses,488,Negative

In [4]:
df.describe()

,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count,Review Length
count,19817.000000,19817.000000,19817.000000,19817.000000,19817.000000,19817.000000
mean,918.049251,43.439824,4.352122,0.876470,2.549780,305.884796
std,204.058778,12.396398,1.092855,0.329053,5.632417,144.421369
min,1.000000,18.000000,1.000000,0.000000,0.000000,9.000000
25%,861.000000,34.000000,4.000000,1.000000,0.000000,183.000000
50%,936.000000,41.000000,5.000000,1.000000,1.000000,297.000000
75%,1078.000000,52.000000,5.000000,1.000000,3.000000,454.000000
max,1205.000000,99.000000,5.000000,1.000000,117.000000,508.000000

In [5]:
df.shape

(19817, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19817 entries, 0 to 19816
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              19817 non-null  int64
 1   Age                      19817 non-null  int64
 2   Title                    17211 non-null  str
 3   Review Text              19817 non-null  str
 4   Rating                   19817 non-null  int64
 5   Recommended IND          19817 non-null  int64
 6   Positive Feedback Count  19817 non-null  int64
 7   Division Name            19817 non-null  str
 8   Department Name          19817 non-null  str
 9   Class Name               19817 non-null  str
 10  Review Length            19817 non-null  int64
 11  Sentiment                19817 non-null  str
dtypes: int64(6), str(6)
memory usage: 8.5 MB

In [7]:
df.isnull().sum()

Clothing ID                   0
Age                           0
Title                      2606
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                 0
Department Name               0
Class Name                    0
Review Length                 0
Sentiment                     0
dtype: int64

In [8]:
df=df.dropna(subset=['Review Text'])

In [9]:
df.isnull().sum()

Clothing ID                   0
Age                           0
Title                      2606
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                 0
Department Name               0
Class Name                    0
Review Length                 0
Sentiment                     0
dtype: int64

In [10]:
x=df['Review Text']
y=df['Recommended IND']

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(15853,)
(3964,)
(15853,)
(3964,)

In [12]:
TF_IDF=TfidfVectorizer(
    stop_words='english',
    max_features=5000,
)
x_train_TfIdf=TF_IDF.fit_transform(x_train)
x_test_TfIdf=TF_IDF.transform(x_test)
print(x_train_TfIdf.shape)
print(x_test_TfIdf)

(15853, 5000)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 89371 stored elements and shape (3964, 5000)>
  Coords	Values
  (0, 401)	0.15738789670248773
  (0, 1005)	0.09914633959900497
  (0, 1048)	0.20838862710448433
  (0, 1253)	0.17935913453300634
  (0, 1515)	0.2669254150082738
  (0, 2062)	0.2850741984011019
  (0, 2609)	0.3608649711207447
  (0, 2641)	0.07552982978109454
  (0, 2902)	0.20175741864475852
  (0, 3000)	0.10577239308015488
  (0, 3098)	0.30437365266908806
  (0, 3611)	0.26962079245304993
  (0, 3848)	0.12354112127729674
  (0, 3850)	0.19487450709548612
  (0, 3861)	0.26321337844819465
  (0, 3953)	0.24886953320179642
  (0, 3955)	0.13920716692966864
  (0, 4292)	0.13073623175018192
  (0, 4440)	0.18518078124290388
  (0, 4608)	0.18291933569593882
  (0, 4725)	0.1482260511709959
  (0, 4896)	0.22919988793868584
  (0, 4934)	0.14472341113732007
  (1, 40)	0.17417897889753728
  (1, 205)	0.15249743415386705
  :	:
  (3962, 3012)	0.3054787638037522
  (3962, 3135)	0.15320952914446379
  (3962, 3220)	0.3959689614067596
  (3962, 3331)	0.23569187742162437
  (3962, 4263)	0.3075874003811886
  (3962, 4828)	0.12910694680821772
  (3962, 4842)	0.40812276699067385
  (3962, 4925)	0.18969332020634175
  (3963, 616)	0.20047877905625006
  (3963, 919)	0.3350973374565234
  (3963, 1424)	0.16063624616343997
  (3963, 1608)	0.3842279921813039
  (3963, 1649)	0.12257799827782427
  (3963, 2347)	0.21774746756415161
  (3963, 2614)	0.12990276248684993
  (3963, 2693)	0.18368208767493815
  (3963, 2924)	0.2780206651421082
  (3963, 3149)	0.15578527349494203
  (3963, 3457)	0.2662076352295184
  (3963, 3581)	0.22274539906310267
  (3963, 3911)	0.2796085472994357
  (3963, 4353)	0.2759875582610248
  (3963, 4779)	0.20625404516725573
  (3963, 4824)	0.1648609197796242
  (3963, 4891)	0.33898854271983603

In [13]:
svm_model = SVC(kernel='linear', C=0.09,random_state=42)
svm_model.fit(x_train_TfIdf, y_train)

SVC(C=0.09, kernel='linear', random_state=42)

In [14]:
y_pred = svm_model.predict(x_test_TfIdf)

In [15]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of SVM: {accuracy:.2f}")

Accuracy of SVM: 0.88

In [18]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy=accuracy_score(y_test,y_pred)
print(f'accuracy: {accuracy}')
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

accuracy: 0.8849646821392533
Precision: 0.8842828077314344
Recall: 0.9997124784358827
F1 Score: 0.9384615384615385

In [17]:
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[  31  455]
 [   1 3477]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.06      0.12       486
           1       0.88      1.00      0.94      3478

    accuracy                           0.88      3964
   macro avg       0.93      0.53      0.53      3964
weighted avg       0.89      0.88      0.84      3964