Linear SVC Model

In [109]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import  precision_score
from sklearn.metrics import   recall_score
from sklearn.metrics import   f1_score

In [110]:
df = pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv')

In [111]:
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [112]:
df.describe()

,Unnamed: 0,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,11742.500000,918.118709,43.198544,4.196032,0.822362,2.535936
std,6779.968547,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,0.000000,18.000000,1.000000,0.000000,0.000000
25%,5871.250000,861.000000,34.000000,4.000000,1.000000,0.000000
50%,11742.500000,936.000000,41.000000,5.000000,1.000000,1.000000
75%,17613.750000,1078.000000,52.000000,5.000000,1.000000,3.000000
max,23485.000000,1205.000000,99.000000,5.000000,1.000000,122.000000

In [113]:
df.shape

(23486, 11)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [115]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [116]:
df=df.dropna(subset=['Review Text'])

In [117]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      2966
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                13
Department Name              13
Class Name                   13
dtype: int64

In [118]:
x=df['Review Text']
y=df['Recommended IND']

In [119]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(18112,)
(4529,)
(18112,)
(4529,)

In [120]:
TF_IDF=TfidfVectorizer(
    stop_words='english',
    max_features=5000,
)
x_train_TfIdf=TF_IDF.fit_transform(x_train)
x_test_TfIdf=TF_IDF.transform(x_test)
print(x_train_TfIdf.shape)
print(x_test_TfIdf)

(18112, 5000)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 102236 stored elements and shape (4529, 5000)>
  Coords	Values
  (0, 520)	0.1330168993994457
  (0, 650)	0.19319722593486166
  (0, 1059)	0.26691593761425975
  (0, 1303)	0.1601910074025413
  (0, 1382)	0.16171805429268762
  (0, 1720)	0.0980825549994578
  (0, 1721)	0.26803630953766566
  (0, 1746)	0.12531202976196293
  (0, 1985)	0.1772173264339828
  (0, 2369)	0.11000404437585339
  (0, 2573)	0.12273263596951395
  (0, 2643)	0.17577204382607725
  (0, 2675)	0.136302722398053
  (0, 2876)	0.18709230148593878
  (0, 2895)	0.1824821689328888
  (0, 2968)	0.18449881833738466
  (0, 2969)	0.12347164197640889
  (0, 3104)	0.12431855025032665
  (0, 3486)	0.2920119294557698
  (0, 3501)	0.2592516985033171
  (0, 3923)	0.19051670814503482
  (0, 3967)	0.18905612299972047
  (0, 3984)	0.23945348348940204
  (0, 4311)	0.3005462835542838
  (0, 4565)	0.15486488589454028
  :	:
  (4528, 3007)	0.2495704249539091
  (4528, 3076)	0.1352681528759238
  (4528, 3224)	0.20994258205229344
  (4528, 3318)	0.1440277008412851
  (4528, 3407)	0.2127410163829236
  (4528, 3448)	0.18649366263961956
  (4528, 3696)	0.14940044520837073
  (4528, 3697)	0.1263350594500251
  (4528, 3847)	0.1095101945113224
  (4528, 3870)	0.1676717808361629
  (4528, 3923)	0.14300887042743676
  (4528, 3958)	0.12057656285957152
  (4528, 4123)	0.21084860551675322
  (4528, 4187)	0.11234620406819464
  (4528, 4217)	0.22966106789343474
  (4528, 4311)	0.11280056468732974
  (4528, 4355)	0.1512187649546705
  (4528, 4444)	0.16425921457929576
  (4528, 4445)	0.11014590056520243
  (4528, 4556)	0.2242214858776794
  (4528, 4638)	0.1431200792399242
  (4528, 4668)	0.18948809827948196
  (4528, 4825)	0.07730792315410538
  (4528, 4902)	0.17597812635904234
  (4528, 4958)	0.2275028881899767

In [121]:
svm_model = SVC(kernel='linear', C=0.09,random_state=42)
svm_model.fit(x_train_TfIdf, y_train)

SVC(C=0.09, kernel='linear', random_state=42)

In [122]:
y_pred = svm_model.predict(x_test_TfIdf)

In [123]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of SVM: {accuracy:.2f}")

Accuracy of SVM: 0.85

In [124]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.8507943817637578
Recall: 0.9940812483185365
F1 Score: 0.9168734491315137

In [125]:
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[ 164  648]
 [  22 3695]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.20      0.33       812
           1       0.85      0.99      0.92      3717

    accuracy                           0.85      4529
   macro avg       0.87      0.60      0.62      4529
weighted avg       0.86      0.85      0.81      4529